/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/GMYA.glb --transform 
Files: public/3D/GMYA.glb [109.14KB] > G:\Web mpk kimi\Kimi_Agent_Situs MPK\app\GMYA-transformed.glb [27.92KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/GMYA-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} rotation={[0, 1.484, 0]} />
    </group>
  )
}

useGLTF.preload('/GMYA-transformed.glb')
